# Generated by Django 6.0.4 on 2026-04-14 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('SRVUID', models.UUIDField(db_column='SRVUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SRVNME', models.CharField(db_column='SRVNME', help_text='Service name (e.g., resume_analyzer)', max_length=100, unique=True)),
                ('SRVTPE', models.CharField(choices=[('AI', 'AI Service'), ('UTILITY', 'Utility'), ('API', 'External API')], db_column='SRVTPE', default='AI', max_length=20)),
                ('SRVDSC', models.TextField(blank=True, db_column='SRVDSC', help_text='Service description')),
                ('ISACTV', models.BooleanField(db_column='ISACTV', default=True)),
                ('CONFIG', models.JSONField(blank=True, db_column='CONFIG', default=dict, help_text='Service configuration')),
                ('CRETDT', models.DateTimeField(auto_now_add=True, db_column='CRETDT')),
                ('UPDTDT', models.DateTimeField(auto_now=True, db_column='UPDTDT')),
            ],
            options={
                'db_table': 'SRV_MST',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('RQLUID', models.UUIDField(db_column='RQLUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SRVNME', models.CharField(db_column='SRVNME', max_length=100)),
                ('INPDTA', models.JSONField(db_column='INPDTA', help_text='Input data')),
                ('OUTDTA', models.JSONField(blank=True, db_column='OUTDTA', help_text='Output data', null=True)),
                ('STATUS', models.CharField(db_column='STATUS', default='SUCCESS', max_length=20)),
                ('ERRMSG', models.TextField(blank=True, db_column='ERRMSG')),
                ('RESPMS', models.IntegerField(db_column='RESPMS', help_text='Response time in milliseconds')),
                ('CRETDT', models.DateTimeField(auto_now_add=True, db_column='CRETDT')),
                ('USRUID', models.ForeignKey(db_column='USRUID', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RQL_MST',
                'ordering': ['-CRETDT'],
            },
        ),
    ]
