# Generated by Django 6.0.4 on 2026-04-09 06:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_column='USRUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='EMLID', max_length=255, unique=True)),
                ('name', models.CharField(db_column='USRNM', max_length=255)),
                ('password', models.CharField(db_column='PASWRD', max_length=128)),
                ('is_active', models.BooleanField(db_column='ISACTV', default=True)),
                ('is_staff', models.BooleanField(db_column='ISSTAF', default=False)),
                ('is_superuser', models.BooleanField(db_column='ISSUPR', default=False)),
                ('created_at', models.DateTimeField(db_column='CRETDT', default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, db_column='LSTLGN', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USR_MST',
            },
        ),
    ]
