# Generated by Django 6.0.4 on 2026-04-12 15:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('PLNUID', models.UUIDField(db_column='PLNUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PLNNME', models.CharField(db_column='PLNNME', help_text='Plan name (e.g., Free, Pro)', max_length=100, unique=True)),
                ('PLNPRI', models.DecimalField(db_column='PLNPRI', decimal_places=2, default=0.0, help_text='Plan price in INR', max_digits=10)),
                ('USGLIM', models.IntegerField(db_column='USGLIM', help_text='Usage limit per month')),
                ('DURATN', models.IntegerField(db_column='DURATN', default=30, help_text='Duration in days')),
                ('ISACTV', models.BooleanField(db_column='ISACTV', default=True, help_text='Is plan active')),
                ('CRETDT', models.DateTimeField(auto_now_add=True, db_column='CRETDT')),
                ('UPDTDT', models.DateTimeField(auto_now=True, db_column='UPDTDT')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'PLN_MST',
                'ordering': ['PLNPRI'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('SUBUID', models.UUIDField(db_column='SUBUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('STRDAT', models.DateTimeField(db_column='STRDAT', default=django.utils.timezone.now)),
                ('ENDDAT', models.DateTimeField(db_column='ENDDAT')),
                ('SUBSTS', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_column='SUBSTS', default='ACTIVE', max_length=20)),
                ('CRETDT', models.DateTimeField(auto_now_add=True, db_column='CRETDT')),
                ('UPDTDT', models.DateTimeField(auto_now=True, db_column='UPDTDT')),
                ('PLNUID', models.ForeignKey(db_column='PLNUID', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('USRUID', models.ForeignKey(db_column='USRUID', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'SUB_MST',
                'ordering': ['-CRETDT'],
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('USGUID', models.UUIDField(db_column='USGUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SRVTYP', models.CharField(choices=[('GENERIC', 'Generic Service')], db_column='SRVTYP', default='GENERIC', max_length=50)),
                ('USGCNT', models.IntegerField(db_column='USGCNT', default=0, help_text='Usage count for current month')),
                ('RSTMON', models.CharField(db_column='RSTMON', help_text='Reset month (YYYY-MM)', max_length=7)),
                ('CRETDT', models.DateTimeField(auto_now_add=True, db_column='CRETDT')),
                ('UPDTDT', models.DateTimeField(auto_now=True, db_column='UPDTDT')),
                ('USRUID', models.ForeignKey(db_column='USRUID', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage',
                'verbose_name_plural': 'Usages',
                'db_table': 'USG_MST',
                'ordering': ['-RSTMON'],
                'unique_together': {('USRUID', 'SRVTYP', 'RSTMON')},
            },
        ),
    ]
